### ISSUE TITLE
Notifications for feeds?

### ISSUE THREAD

**Issue by rmenessec** [enricocid/iven-feed-reader#12]
It would be great to be able to receive status bar notifications and audio alerts when there are new items - preferably as a per-feed setting.

This is a fantastic aggregator. Thanks so much for working on this.

**Comment by supportreq** [comment]
this will be a superb feature..

**Comment by enricocid** [comment]
I'll look into this asap, but consider that currently I don't have a personal pc and i'm busy with work.

next time please use the mail to send a feature request.
Issues section is for issues, i.e. bugs, crash reports etc etc
