### ISSUE TITLE
getting no resource identifier found error 

### ISSUE THREAD

**Issue by suds7** [enricocid/iven-feed-reader#20]
I keep getting no resource identifier found error message, usually when i clean project or rebuild project then this error get away but even after rebuilding project/clean project multiple times no luck. 
I'm using the 24.0.2 version my build.gradle file is 

dependencies {
    compile 'com.android.support:appcompat-v7:24.0.0'
    compile 'org.jsoup:jsoup:1.10.2'
    compile 'com.android.support:support-v4:24.0.0'
    compile 'com.github.bumptech.glide:glide:3.7.0'
} 

Error message:
Error:(16) No resource identifier found for attribute 'roundIcon' in package 'android'

Can anyone please help me?

**Comment by enricocid** [comment]
roundIcon was added in android N

You have to update to v 25

**Comment by suds7** [comment]
Thanks it did fixed the issue.
