### ISSUE TITLE
Cannot switch between feeds

### ISSUE THREAD

**Issue by gadgetguy08** [enricocid/iven-feed-reader#22]
Just upgraded to 3.1. App opens feed, but won't switch to another feed without exiting and restarting. Didn't do this on prior version.

06-21 06:25:26.233 I/ActivityManager(1137): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.iven.lfflfeedreader/.mainact.SplashActivity bnds=[74,1198][324,1484] (has extras)} from uid 10125 on display 0
06-21 06:25:34.300 V/ActivityManager(1137): Attempted to start a foreground service (ComponentInfo{com.iven.lfflfeedreader/com.iven.lfflfeedreader.utils.notifyService}) with a broken notification (no icon: Notification(pri=0 contentView=com.iven.lfflfeedreader/0x1090085 vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
06-21 06:25:34.305 D/ZenLog  (1137): intercepted: 0|com.iven.lfflfeedreader|101|null|10199,!priority
06-21 06:25:34.306 V/NotificationService(1137): pkg=com.iven.lfflfeedreader canInterrupt=false intercept=true

**Comment by enricocid** [comment]
Thanks. Gonna watch into this issue this monday (i'm out).

**Comment by gadgetguy08** [comment]
Version 3.2 is handling this properly.
You may close this.
Thanks.
