### ISSUE TITLE
English

### ISSUE THREAD

**Issue by amilopowers** [enricocid/iven-feed-reader#9]
Is there a way to change the language from Spanish to English or different languages?

Additionally I would love to see a possibility to choose news sources.

Thanks for the great app!

**Comment by enricocid** [comment]
" Is there a way to change the language from Spanish to English or different languages? "

You should set English from Your device, anyway i will try to add an option to force English language

" I would love to see a possibility to choose news sources."

I'm already working on it, but it's still under heavy developments  :)

**Comment by amilopowers** [comment]
My phone runs usually in German but when I change the system language to English-US and reboot my device the app still runs in Spanish...

**Comment by enricocid** [comment]
strange

for german you should translate this 

https://github.com/enricocid/lffl-feed-reader/blob/master-as/project/app/src/main/res/values/strings.xml

send to me, and then i will include into the app

**Comment by amilopowers** [comment]
With update 7.1 it changed to English! Can be closed.
